[package]
name = "tapestry-loom"
version = "0.0.0"
authors = [
	"transkatgirl",
]
license = "AGPL-3.0-or-later"
description = "An IDE for working with base model LLMs."
edition = "2024"

[dependencies]
tapestry-weave = { path = "universal-weave/tapestry-weave", features = [
	"serde",
] }
eframe = { workspace = true, features = [
  "default",
] }
egui_extras = { workspace = true, features = ["default", "image"] }
env_logger = { workspace = true, features = ["auto-color", "humantime"] }
serde = { version = "1.0.228", features = [
	"derive",
] }
serde_json = "1.0.145"
reqwest = { version = "0.12", features = [
	"json",
] }
parking_lot = { version = "0.12.5", features = [
	"serde",
] }
anyhow = "1.0.100"
thiserror = "2.0.17"
