[package]
name = "tapestry-loom"
version = "0.0.0"
authors = [
	"transkatgirl",
]
license = "AGPL-3.0-or-later"
description = "An IDE for working with base model LLMs."
edition = "2024"

[dependencies]
tapestry-weave = { path = "universal-weave/tapestry-weave", features = [
	"serde",
] }
eframe = { version = "0.33.2", features = [
	"persistence",
] }
env_logger = { version = "0.11.8", features = ["auto-color", "humantime"] }
serde = { version = "1.0.228", features = [
	"derive",
] }
serde_json = { version = "1.0.145", features = [
	"preserve-order",
] }
toml = { version = "0.9.8", features = [
	"preserve-order",
] }
ron = { version = "0.12.0", features = ["indexmap", "integer128", "unicode-segmentation"] }
reqwest = { version = "0.12", features = [
	"json",
] }
parking_lot = { version = "0.12.5", features = [
	"serde",
] }
anyhow = "1.0.100"
thiserror = "2.0.17"
